---
name: Kustomize
description: Thin wrapper for installing kustomize
inputs:
  version:
    description: Version of Kustomize to use
    required: false
    default: 4.5.5
  sha256-checksum:
    description: Checksum of customize version
    required: false
    default: bba81aa61dba057db1d5abeddf1e522b568b2d906ab67a5c80935e97302c8773
runs:
  using: composite
  steps:
    - name: Cache
      id: cache
      uses: actions/cache@v3
      with:
        path: /tmp/bin/kustomize_v${{ inputs.version }}_linux_amd64.tar.gz
        key: kustomize-${{ inputs.version }}-${{ inputs.sha256-checksum }}
    - run: |
        mkdir -p /tmp/bin
        pushd /tmp/bin

        if [ -f "${KUSTOMIZE_FILENAME}" ]; then
          echo "Kustomize already downloaded"
        else
          curl -o "${KUSTOMIZE_FILENAME}" -L "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${VERSION}/${KUSTOMIZE_FILENAME}"
        fi
        sha256sum "${KUSTOMIZE_FILENAME}"

        echo "${SHA256_CHECKSUM}  ${KUSTOMIZE_FILENAME}" > kustomize.SHA256
        sha256sum -c kustomize.SHA256
        tar xzf "${KUSTOMIZE_FILENAME}"
        chmod u+x kustomize
        popd

        echo "/tmp/bin" >> $GITHUB_PATH
        /tmp/bin/kustomize version
        kustomize version
      shell: bash
      env:
        KUSTOMIZE_FILENAME: /tmp/bin/kustomize_v${{ inputs.version }}_linux_amd64.tar.gz
        SHA256_CHECKSUM: ${{ inputs.sha256-checksum }}
        VERSION: ${{ inputs.version }}
