---
name: Kustomize
description: Thin wrapper for installing kustomize
inputs:
  version:
    description: Version of Kustomize to use
    required: false
    default: 4.5.5
  sha256-checksum:
    description: Checksum of customize version
    required: false
    default: bba81aa61dba057db1d5abeddf1e522b568b2d906ab67a5c80935e97302c8773
runs:
  using: composite
  steps:
    - run: |
        mkdir -p /tmp/bin
        pushd /tmp/bin
        KUSTOMIZE_FILENAME="kustomize_v${{ inputs.version }}_linux_amd64.tar.gz"
        curl -o ${KUSTOMIZE_FILENAME} -L https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${{ inputs.version }}/${KUSTOMIZE_FILENAME}
        sha256sum ${KUSTOMIZE_FILENAME}
        echo "${{ inputs.sha256-checksum }}  ${KUSTOMIZE_FILENAME}" > kustomize.SHA256
        sha256sum -c kustomize.SHA256
        tar xzf ${KUSTOMIZE_FILENAME}
        chmod u+x kustomize
        popd
        echo "/tmp/bin/" >> $GITHUB_PATH
        kustomize version
      shell: bash
