---
name: Kustomize
description: Thin wrapper for installing kustomize
inputs:
  version:
    description: Version of Kustomize to use
    required: false
    default: 5.0.0
  sha256-checksum:
    description: Checksum of customize version
    required: false
    default: 2e8c28a80ce213528251f489db8d2dcbea7c63b986c8f7595a39fc76ff871cd7
runs:
  using: composite
  steps:
    # - name: Cache
    #   id: cache
    #   uses: actions/cache@v3
    #   with:
    #     path: /tmp/bin/kustomize_v${{ inputs.version }}_linux_amd64.tar.gz
    #     key: kustomize-${{ inputs.version }}-${{ inputs.sha256-checksum }}
    - name: Download and Checksum Kustomize
      shell: bash
      run: |-
        mkdir -p "${BIN_DIR}"
        pushd "${BIN_DIR}" || exit 1

        set -e

        KUSTOMIZE_DOWNLOAD_PATH="${BIN_DIR}/${KUSTOMIZE_FILENAME}"

        if [ -f "${KUSTOMIZE_DOWNLOAD_PATH}" ]; then
            echo "Kustomize already downloaded"
        else
            curl -o "${KUSTOMIZE_FILENAME}" -L "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${VERSION}/${KUSTOMIZE_FILENAME}"
        fi
        sha256sum "${KUSTOMIZE_FILENAME}"
        echo "${SHA256_CHECKSUM}  ${KUSTOMIZE_FILENAME}" > kustomize.SHA256
        sha256sum -c kustomize.SHA256
        tar xzf "${KUSTOMIZE_FILENAME}"
        chmod u+x kustomize
        popd

        echo "${BIN_DIR}" >> $GITHUB_PATH
        "${BIN_DIR}/kustomize" version
        kustomize version
      env:
        BIN_DIR: /tmp/bin
        KUSTOMIZE_FILENAME: kustomize_v${{ inputs.version }}_linux_amd64.tar.gz
        SHA256_CHECKSUM: ${{ inputs.sha256-checksum }}
        VERSION: ${{ inputs.version }}
