---
name: Kustomize
description: Thin wrapper for installing kustomize
inputs:
  version:
    description: Version of Kustomize to use
    required: false
    default: 5.0.0
  sha256-checksum:
    description: Checksum of customize version
    required: false
    default: 2e8c28a80ce213528251f489db8d2dcbea7c63b986c8f7595a39fc76ff871cd7
runs:
  using: composite
  steps:
    - name: Cache
      id: cache
      uses: actions/cache@v3
      with:
        path: /tmp/bin/kustomize_v${{ inputs.version }}_linux_amd64.tar.gz
        key: kustomize-${{ inputs.version }}-${{ inputs.sha256-checksum }}
    - name: Download and Checksum Kustomize
      run: bash download-and-verify.sh
      shell: bash
      env:
        KUSTOMIZE_FILENAME: /tmp/bin/kustomize_v${{ inputs.version }}_linux_amd64.tar.gz
        SHA256_CHECKSUM: ${{ inputs.sha256-checksum }}
        VERSION: ${{ inputs.version }}
