name: Testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-setup:
    name: Test Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Kustomize Setup
        uses: ./
        
      - name: Kustomize Init and Build
        run: |
          kustomize init
          kustomize build .
